version: '3.4'

services:
  wilwa-website:
    build:
      target: codedev
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file: ../WilWa.Website/devHttps.env
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
    volumes:
      - ..:/app